version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  verify-build:
    executor:
      name: node/default
    steps:
      - checkout
      # Installs dependencies without touching the lockfile.
      - run: yarn install --immutable
      # Build all packages to verify that there are are ok.
      - run: yarn build
      - run: yarn test
      - run: yarn lint
workflows:
  integration:
    jobs:
      - verify-build
