import { Vec2 } from '@heliks/tiles-engine';


export enum CursorButton {
  /** The main button, usually the left button or the un-initialized state */
  Primary = 'cursor_primary',
  /** The Secondary button, usually the right button */
  Secondary = 'cursor_secondary',
  /** Auxiliary button, usually the wheel button or the middle button */
  Auxiliary = 'cursor_auxiliary'
}

export enum PointerType {
  /** Pointer events are generated by a mouse device. */
  Mouse = 'mouse',
  /** Pointer events are generated by a stylus device. */
  Pen = 'pen',
  /** Pointer events are generated by a touch, such as fingers. */
  Touch = 'touch'
}

/** Resource that tracks the mouse cursor. */
export class Cursor {

  /** Contains all buttons that are currently pressed down. */
  public readonly down = new Set<CursorButton>();

  /** Contains all buttons just pressed on the last frame.*/
  public readonly downNow = new Set<CursorButton>();

  /** Contains all buttons released on the last frame. */
  public readonly up = new Set<CursorButton>();

  /** Contains the cursors' last known screen position.*/
  public readonly screen = new Vec2();

  /** Contains the cursors' last known world position. */
  public readonly world = new Vec2();

  /**
   * Contains the current pointer type.
   *
   * The pointer type changes when the user triggers a `pointerdown` event using a
   * different hardware device.
   */
  public type = PointerType.Mouse;

  /** Returns `true` when the given `button` is pressed down. */
  public isDown(button = CursorButton.Primary): boolean {
    return this.down.has(button);
  }

  /** Returns `true` when the given `button` was just pressed on the last frame. */
  public isDownNow(button = CursorButton.Primary): boolean {
    return this.downNow.has(button);
  }

  /** Returns `true` if the given `button` was just released on the last frame. */
  public isUp(button = CursorButton.Primary): boolean {
    return this.up.has(button);
  }

}

